name: neuron
channels:
  - conda-forge
  - defaults
dependencies:
  - _pytorch_select=0.1
  - blas=2.116
  - blas-devel=3.9.0
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - colorama=0.4.6
  - freetype=2.12.1
  - jpeg=9e
  - lcms2=2.15
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=16.0.4
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.45.3
  - libtiff=4.5.0
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - llvm-openmp=16.0.4
  - lz4-c=1.9.4
  - mpi=1.0
  - mpich=4.1.1
  - ncurses=6.4
  - ninja=1.11.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openblas=0.3.21
  - openssl=3.1.0
  - opt_einsum=3.3.0
  - pandoc=3.1.2
  - pip=24.0
  - pyro-api=0.1.2
  - python=3.9.16
  - python_abi=3.9
  - pytz=2024.1
  - readline=8.2
  - six=1.16.0
  - sqlite=3.45.3
  - tbb=2021.9.0
  - tk=8.6.14
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - anyio==4.3.0
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - asttokens==2.4.1
      - attrs==23.2.0
      - babel==2.15.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - bottleneck==1.3.8
      - cffi==1.16.0
      - colorednoise==2.2.0
      - comm==0.2.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - datetime==5.5
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - entrypoints==0.4
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - filelock==3.14.0
      - find-libpython==0.4.0
      - fonttools==4.51.0
      - fsspec==2024.5.0
      - hmmlearn==0.3.2
      - httpcore==1.0.5
      - httpx==0.27.0
      - idna==3.7
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - ipykernel==6.29.4
      - ipython==8.18.1
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.2
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - json5==0.9.25
      - jsonschema==4.22.0
      - jupyter==1.0.0
      - jupyter-client==8.6.1
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.1
      - jupyterlab-widgets==3.0.10
      - kaleido==0.2.1
      - kiwisolver==1.4.5
      - llvmlite==0.42.0
      - lxml==5.2.2
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - mpmath==1.3.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - neuron==8.2.4
      - notebook==7.2.0
      - notebook-shim==0.2.4
      - numba==0.59.1
      - numexpr==2.10.0
      - packaging==24.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.3.0
      - platformdirs==4.2.2
      - plotly==5.22.0
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.43
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycparser==2.22
      - pygments==2.18.0
      - pyparsing==3.1.2
      - pyro-ppl==1.9.0
      - pyrsistent==0.20.0
      - python-dateutil==2.9.0.post0
      - pyzmq==26.0.3
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - referencing==0.35.1
      - requests==2.32.2
      - rpds-py==0.18.1
      - scikit-learn==1.5.0
      - scipy==1.13.0
      - seaborn==0.13.2
      - send2trash==1.8.3
      - setuptools==70.0.0
      - sniffio==1.3.1
      - soupsieve==2.5
      - stack-data==0.6.3
      - sympy==1.12
      - tenacity==8.3.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.3.0
      - torch==2.0.1
      - tornado==6.4
      - tqdm==4.66.4
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20240316
      - tzdata==2024.1
      - urllib3==2.2.1
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.10
      - zipp==3.18.2
      - zope-interface==6.4
